/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form.Inicio;

/**
 *
 * @author jala
 */
public class Task extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Task.class.getName());

    /**
     * Creates new form Task
     */
    public Task() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        BackGround2 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        TeamButton = new javax.swing.JButton();
        Username = new javax.swing.JLabel();
        PendingSection = new javax.swing.JPanel();
        Option1 = new javax.swing.JLabel();
        SeePendingTasks = new javax.swing.JLabel();
        InProgressSection = new javax.swing.JPanel();
        Option2 = new javax.swing.JLabel();
        SeeInProgressTasks = new javax.swing.JLabel();
        DoneSection = new javax.swing.JPanel();
        Option3 = new javax.swing.JLabel();
        SeeDoneTasks = new javax.swing.JLabel();
        CancelledSection = new javax.swing.JPanel();
        Option4 = new javax.swing.JLabel();
        SeeCancelledTasks = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        LogOut = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        BackGround.setBackground(new java.awt.Color(31, 164, 206));
        BackGround.setPreferredSize(new java.awt.Dimension(700, 600));

        BackGround2.setBackground(new java.awt.Color(18, 54, 75));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/Images/Logo.jpeg"))); // NOI18N

        TeamButton.setBackground(new java.awt.Color(20, 105, 136));
        TeamButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        TeamButton.setForeground(new java.awt.Color(255, 255, 255));
        TeamButton.setText("Team");
        TeamButton.setBorder(null);
        TeamButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamButtonActionPerformed(evt);
            }
        });

        Username.setFont(new java.awt.Font("Adumu", 1, 36)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username.setText("Username");

        javax.swing.GroupLayout BackGround2Layout = new javax.swing.GroupLayout(BackGround2);
        BackGround2.setLayout(BackGround2Layout);
        BackGround2Layout.setHorizontalGroup(
            BackGround2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGround2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(BackGround2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logo))
                .addGap(18, 18, 18))
            .addGroup(BackGround2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(TeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackGround2Layout.setVerticalGroup(
            BackGround2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGround2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Logo)
                .addGap(29, 29, 29)
                .addComponent(Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        PendingSection.setBackground(new java.awt.Color(20, 105, 136));
        PendingSection.setForeground(new java.awt.Color(20, 105, 136));

        Option1.setFont(new java.awt.Font("SansSerif", 1, 27)); // NOI18N
        Option1.setForeground(new java.awt.Color(255, 255, 255));
        Option1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Option1.setText("Pending");

        SeePendingTasks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/Images/ojo.png"))); // NOI18N
        SeePendingTasks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout PendingSectionLayout = new javax.swing.GroupLayout(PendingSection);
        PendingSection.setLayout(PendingSectionLayout);
        PendingSectionLayout.setHorizontalGroup(
            PendingSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PendingSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Option1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(SeePendingTasks)
                .addContainerGap())
        );
        PendingSectionLayout.setVerticalGroup(
            PendingSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PendingSectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PendingSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeePendingTasks)
                    .addGroup(PendingSectionLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Option1)))
                .addGap(21, 21, 21))
        );

        InProgressSection.setBackground(new java.awt.Color(20, 105, 136));
        InProgressSection.setForeground(new java.awt.Color(20, 105, 136));

        Option2.setFont(new java.awt.Font("SansSerif", 1, 27)); // NOI18N
        Option2.setForeground(new java.awt.Color(255, 255, 255));
        Option2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Option2.setText("In Progress");

        SeeInProgressTasks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/Images/ojo.png"))); // NOI18N
        SeeInProgressTasks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout InProgressSectionLayout = new javax.swing.GroupLayout(InProgressSection);
        InProgressSection.setLayout(InProgressSectionLayout);
        InProgressSectionLayout.setHorizontalGroup(
            InProgressSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InProgressSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Option2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SeeInProgressTasks)
                .addContainerGap())
        );
        InProgressSectionLayout.setVerticalGroup(
            InProgressSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InProgressSectionLayout.createSequentialGroup()
                .addGroup(InProgressSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InProgressSectionLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Option2))
                    .addGroup(InProgressSectionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SeeInProgressTasks)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        DoneSection.setBackground(new java.awt.Color(20, 105, 136));
        DoneSection.setForeground(new java.awt.Color(20, 105, 136));

        Option3.setFont(new java.awt.Font("SansSerif", 1, 27)); // NOI18N
        Option3.setForeground(new java.awt.Color(255, 255, 255));
        Option3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Option3.setText("Done");

        SeeDoneTasks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/Images/ojo.png"))); // NOI18N
        SeeDoneTasks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout DoneSectionLayout = new javax.swing.GroupLayout(DoneSection);
        DoneSection.setLayout(DoneSectionLayout);
        DoneSectionLayout.setHorizontalGroup(
            DoneSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoneSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Option3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SeeDoneTasks)
                .addContainerGap())
        );
        DoneSectionLayout.setVerticalGroup(
            DoneSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoneSectionLayout.createSequentialGroup()
                .addGroup(DoneSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DoneSectionLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Option3))
                    .addGroup(DoneSectionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SeeDoneTasks)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        CancelledSection.setBackground(new java.awt.Color(20, 105, 136));
        CancelledSection.setForeground(new java.awt.Color(20, 105, 136));

        Option4.setFont(new java.awt.Font("SansSerif", 1, 27)); // NOI18N
        Option4.setForeground(new java.awt.Color(255, 255, 255));
        Option4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Option4.setText("Cancelled");

        SeeCancelledTasks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/Images/ojo.png"))); // NOI18N
        SeeCancelledTasks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout CancelledSectionLayout = new javax.swing.GroupLayout(CancelledSection);
        CancelledSection.setLayout(CancelledSectionLayout);
        CancelledSectionLayout.setHorizontalGroup(
            CancelledSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelledSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Option4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SeeCancelledTasks)
                .addContainerGap())
        );
        CancelledSectionLayout.setVerticalGroup(
            CancelledSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelledSectionLayout.createSequentialGroup()
                .addGroup(CancelledSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CancelledSectionLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Option4))
                    .addGroup(CancelledSectionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SeeCancelledTasks)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        Titulo.setFont(new java.awt.Font("Adumu", 1, 36)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Tasks");

        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/Images/cerrar-sesion.png"))); // NOI18N
        LogOut.setFocusTraversalPolicyProvider(true);

        AddButton.setBackground(new java.awt.Color(20, 105, 136));
        AddButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Add");
        AddButton.setBorder(null);
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(BackGround2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackGroundLayout.createSequentialGroup()
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackGroundLayout.createSequentialGroup()
                                .addGap(407, 407, 407)
                                .addComponent(LogOut))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackGroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(InProgressSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DoneSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CancelledSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PendingSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackGroundLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PendingSection, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InProgressSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoneSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelledSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Task().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel BackGround2;
    private javax.swing.JPanel CancelledSection;
    private javax.swing.JPanel DoneSection;
    private javax.swing.JPanel InProgressSection;
    private javax.swing.JLabel LogOut;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Option1;
    private javax.swing.JLabel Option2;
    private javax.swing.JLabel Option3;
    private javax.swing.JLabel Option4;
    private javax.swing.JPanel PendingSection;
    private javax.swing.JLabel SeeCancelledTasks;
    private javax.swing.JLabel SeeDoneTasks;
    private javax.swing.JLabel SeeInProgressTasks;
    private javax.swing.JLabel SeePendingTasks;
    private javax.swing.JButton TeamButton;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Username;
    // End of variables declaration//GEN-END:variables
}
