USE to_do_capstone;
Go

ALTER TABLE TaskUser
ALTER COLUMN Team_id INT NULL;

ALTER TABLE TaskDetail 
ADD Active BIT DEFAULT 1;

ALTER TABLE Category 
ADD Active BIT DEFAULT 1;

ALTER TABLE Category
ALTER COLUMN Active bit NOT NULL;

GO